import pickle as pkl

log_file = "log.pkl"
with open(log_file, 'rb') as fh:
    log = pkl.load(fh)

print(log)

def get_radius(log):
    ...
def get_ground_distance(log, r0):
    ...
def get_r_dot(log):
    ...
def get_v_theta(log):
    ...
def get_r_dot_dot(log):
    ...
def get_a_theta(log):
    ...
def get_orbital_elements(log):
    ...
def get_alpha(log):
    ...
