site_name: KAGP Docs
theme:
  name: readthedocs
  custom_dir: mathjax_template/
nav:
  - KAGP:
    - index.md
    - inputs.md
  - Implementation: 
    - Guidance Objects: 'implementation_docs/guidance_objects.md'
    - Guidance Components: 'implementation_docs/guidance_components.md'
  - Appendices:
    - A. Reference Symbols: 'implementation_docs/A_symbols.md'
    - B. Reference Frames: 'implementation_docs/B_reference_frames.md'
    - C. Guidance Derivation: 'implementation_docs/C_abbv_derivation.md'
extra_css:
  - css/fig.css
markdown_extensions:
  - toc:
      permalink: True
  